### PR TITLE
Fixed a variety of bugs causing sync to not work.

### PR DESCRIPTION
**Pull request by laceysanderson**
Issue #11 

Fixed a variety of stupid bugs that were causing the mviews to remain empty after sync'ing.

## Testing

1. Go to Admin > Tripal > Extentions > Natural Diversity Genotypes.
2. Click on the "Sync" tab
3. Choose an organism for which you know you have genotypes and click "Sync"

Check the various mview tables for the genus you sync'd. They should contain recognizable data ;-p
Note: To determine which mview tables there are use `\dt chado.*ndg*` in psql. You should check the calls and variants table with your genus in it as well as the `mview_ndg_germplasm_genotyped` table.

### CODE REVIEW

**Comment by laceysanderson** [comment]
Working on #15 in this PR as well.

**Comment by carolyncaron** [comment]
~~**STILL IN TESTING** (turns out trying to sync all the SNPs from the LDP takes hours, my bad!), however~~ here is what I've noticed thus far:
1. Initially when I ran the syncing, I was getting `Permission denied` errors. This was due to the files being used for copy already exisiting and being owned by you. It was a quick fix by just deleting those files, but perhaps you could come up with a more creative file-naming scheme ;-)
2. My 2nd attempt yielded the following error:
`ERROR:  null value in column "marker_type" violates not-null constraint
DETAIL:  Failing row contains (302536, 355128, LcC00001p404 454 Sequencing, null, 27907, CDC Redberry 454 Extraction, 58, CDC Redberry, 3, 2625647, A, null, 1931321).
CONTEXT:  COPY mview_ndg_lens_calls, line 1: "302536	355128	LcC00001p404 454 Sequencing	\N	27907	CDC Redberry 454 Extraction	58	CDC Redberry	3	262..."`
Also a quick fix since I just have to drop the mview tables and then they'll be recreated properly. But it might be nice to guide a new user through this process or even include an update hook to do it for them 😊

**Review by carolyncaron — COMMENTED** [review]
Other than the two issues mentioned above, this appears to work flawlessly plus I can visualize genotypes from exome capture now using the genotype matrix!!! 🎉 🎉 🎉

**Comment by laceysanderson** [comment]
I've addressed the first item (filename) -Thanks!
As for the second, it turns out that is harder to automate then one might think since the table includes the genus. Since I'm not sure how many (if any) are using this module outside our group, I'm going to include this point in the release notes rather then automate it.

**Pull request merged**
